title: "Marcin Charzyński – Data Analyst Portfolio"
description: "Portfolio showcasing data analysis projects using SQL, Python, Power BI, and Excel."
baseurl: ""
url: "https://marcin-charzynski.github.io"

theme: minima
markdown: kramdown
include:
  - _includes
permalink: pretty

exclude:
  - jekyll-gh-pages.yml
  - README.md
  - LICENSE