title: Marcin Charzyński – Data Analyst Portfolio
description: Portfolio showcasing data analysis projects using SQL, Python, Power BI, and Excel.
baseurl: ""
url: "https://marcin-charzynski.github.io"
theme: minima
markdown: kramdown
include: 
 - _includes
permalink: pretty

kramdown:
  syntax_highlighter_opts:
    line_numbers: true